"use client";

import React, { useMemo, useState } from "react";
import Modal from "../Modal";
import Table from "../Table";
import ResourceCard from "../cards/ResourceCard";
import CustomEditor from "../common/CustomEditor";
import { DateTime } from "luxon";

const ViewAllResourcesModal = ({
  isOpen,
  onClose,
  resources,
  viewAllMode,
  setViewAllMode,
  searchTerm,
  setSearchTerm,
  resourceTypes,
  prompt,
  answer,
}) => {
  const [showAnswer, setShowAnswer] = useState(false);

  const filteredResources = useMemo(() => {
    return resources.filter((resource) => {
      const searchLower = searchTerm.toLowerCase();
      return (
        searchTerm === "" ||
        resource.title?.toLowerCase().includes(searchLower) ||
        resource.description?.toLowerCase().includes(searchLower) ||
        resource.organizations?.some((org) =>
          org.name.toLowerCase().includes(searchLower)
        )
      );
    });
  }, [resources, searchTerm]);

  const columns = useMemo(
    () => [
      {
        accessorKey: "resourceDate",
        header: "DATE",
        cell: (info) => (
          <div className="text-sm">
            {DateTime.fromISO(info.getValue()).toLocaleString(
              DateTime.DATETIME_SHORT
            )}
          </div>
        ),
      },
      {
        accessorKey: "resourceUpdatedDate",
        header: "UPDATED",
        cell: (info) => (
          <div className="text-sm">
            {info.getValue()
              ? DateTime.fromISO(info.getValue()).toLocaleString(
                  DateTime.DATETIME_SHORT
                )
              : "N/A"}
          </div>
        ),
      },
      {
        accessorKey: "name",
        header: "NAME",
        size: 150,
        cell: (info) => (
          <div className="font-medium w-[250px] overflow-clip text-gray-900">
            {info.getValue()}
          </div>
        ),
      },

      {
        accessorKey: "description",
        header: "DESCRIPTION",
        size: 400,
        cell: (info) => (
          <div className="text-sm text-gray-600 max-h-[60px] min-w-[300px] overflow-y-auto">
            <CustomEditor
              content={info.getValue()}
              transparent={true}
              editable={false}
            />
          </div>
        ),
      },
      {
        accessorKey: "organizations",
        header: "ORGANIZATIONS",
        cell: (info) => (
          <div className="text-sm">
            {info
              .getValue()
              ?.map((org) => org.name)
              .join(", ")}
          </div>
        ),
      },
    ],
    []
  );

  if (!isOpen) return null;

  return (
    <Modal onClose={onClose} maxWidth="lg:w-3/4 w-full">
      <div className="text-gray-700 bg-gradient-to-br from-blue-50 to-purple-100 max-h-[90vh] overflow-y-auto flex flex-col rounded-lg">
        <div className="p-8">
          <div className="flex justify-between flex-col sm:flex-row items-start mb-4 mr-4">
            <div className="flex flex-col gap-2 w-full max-h-[250px] overflow-y-auto">
              <h2 className="text-2xl font-bold">All Resources</h2>
              {prompt && (
                <div className="flex flex-col gap-2 w-full">
                  <div className="flex items-center gap-2 flex-col md:flex-row">
                    <div className="text-sm text-gray-600 italic flex-grow overflow-scroll line-clamp-6">
                      {prompt}
                    </div>
                    {answer && (
                      <button
                        onClick={() => setShowAnswer(!showAnswer)}
                        className="text-sm px-2 py-1 rounded bg-blue-100 hover:bg-blue-200 text-blue-700 transition-colors whitespace-nowrap"
                      >
                        {showAnswer ? "Hide Context" : "Show Context"}
                      </button>
                    )}
                  </div>
                  {showAnswer && answer && (
                    <div className="mt-2 p-2 md:p-4 bg-white rounded-lg shadow-sm border border-gray-200 w-full">
                      <div className="mb-3 p-2 bg-gray-50 rounded text-xs text-gray-600 w-full">
                        Note: This response is generated by AI and should not be
                        considered medical advice. Always consult with your
                        healthcare team for professional medical guidance.
                      </div>
                      <p className="text-sm text-gray-700 whitespace-pre-wrap w-full max-h-[200px] overflow-y-auto">
                        {answer}
                      </p>
                    </div>
                  )}
                </div>
              )}
            </div>

            <div className="flex rounded-lg border border-gray-300 p-1 bg-white ml-4 pr-8 mr-8 mt-2">
              <button
                onClick={() => setViewAllMode("grid")}
                className={`px-4 py-2 rounded-md transition-colors ${
                  viewAllMode === "grid"
                    ? "bg-gray-800 text-white"
                    : "text-gray-600 hover:bg-gray-100"
                }`}
              >
                <span className="flex items-center gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" />
                  </svg>
                  Grid
                </span>
              </button>
              <button
                onClick={() => setViewAllMode("table")}
                className={`px-4 py-2 rounded-md transition-colors ${
                  viewAllMode === "table"
                    ? "bg-gray-800 text-white"
                    : "text-gray-600 hover:bg-gray-100"
                }`}
              >
                <span className="flex items-center gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path
                      fillRule="evenodd"
                      d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2z"
                      clipRule="evenodd"
                    />
                  </svg>
                  Table
                </span>
              </button>
            </div>
          </div>

          <div className="mt-4">
            <input
              type="text"
              placeholder="Search resources..."
              className="w-full px-4 py-2 border rounded-lg"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </div>

        <div className="flex-1 overflow-y-auto pl-4 md:pl-8 pr-4 md:pr-8 mb-10">
          {viewAllMode === "grid" ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pb-4">
              {filteredResources.map((resource) => (
                <ResourceCard
                  key={resource.id}
                  resource={resource}
                  resourceTypes={resourceTypes}
                />
              ))}
            </div>
          ) : (
            <div className="h-full">
              <Table data={filteredResources} columns={columns} />
            </div>
          )}
        </div>
      </div>
    </Modal>
  );
};

export default ViewAllResourcesModal;
